[package]
name = "ab-test-sim-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
statrs = "0.16.0"
rand = { version = "0.8.5", features = ["small_rng"] }
